### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by azhang7740** [azhang7740/CalendarApp#3]
Create to-do list view.

- [ ] Create to-do list view controller
- [ ] Connect to Parse backend
- [ ] Create details view for tasks
- [ ] Configure UI for viewing to-do lists
